name: Pregunta 4 pedrivlob
on:
  push:
  workflow_dispatch:
jobs:  
  Build:
    runs-on: ubuntu-latest
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew build
      - name: Muestra uvus por pantalla
        run: echo "pedrivlob"
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Pruebas de test
        run: |
          chmod +x gradlew 
          ./gradlew test
      - name: Muestra uvus por pantalla
        run: echo "pedrivlob"
